---
title: "Titanic Passenger Survival Rates"
author: "Paulina Grunwad"
date: "February 2017"
output: html_document
---


```{r}
#Load packages
require(knitr)
require(markdown)
library(tidyr)
library(dplyr)
library(ggplot2)
library(RColorBrewer)

#Load csv file
titanic <-  tbl_df(read.csv("C:/Personal/GitHub/Udacity-Data-Analyst-Nanodegree/Project 6 - Make Effective Data Visualization/Final project/train.csv"))
```


I will remove columns which i will not use in my investigation.

```{r}
titanic$PassengerId <- NULL
titanic$Cabin <- NULL
titanic$Name <- NULL
titanic$Ticket <- NULL
titanic$Fare <- NULL
titanic$Cabin <- NULL
titanic$SibSp <- NULL
titanic$Parch <- NULL

titanic<- na.omit(titanic)
titanic[complete.cases(titanic),]

```


```{r}
summary(titanic)
```


```{r}
titanic$Age_Type  = ""
titanic$Age_Type[titanic$Age < 18] = "Child"
titanic$Age_Type[titanic$Age >= 18] = "Adult"

titanic$Survived[titanic$Survived == 0] = "Perished"
titanic$Survived[titanic$Survived == 1] = "Survived"

colnames(titanic)[colnames(titanic)=="Pclass"] <- "Class"

titanic$Class[titanic$Class == 1] = "First"
titanic$Class[titanic$Class == 2] = "Second"
titanic$Class[titanic$Class == 3] = "Third"

titanic$Embarked <- as.character(titanic$Embarked)
titanic$Embarked[titanic$Embarked == "S"] = "Southampton"
titanic$Embarked[titanic$Embarked == "Q"] = "Queenstown"
titanic$Embarked[titanic$Embarked == "C"] = "Cherbourg"

titanic$Age_Group   = ""
titanic$Age_Group <- as.character(titanic$Age_group)
titanic$Age_Group[titanic$Age <= 10] = "0-10"
titanic$Age_Group[titanic$Age > 10 & titanic$Age <= 20] = "11-20"
titanic$Age_Group[titanic$Age > 20 & titanic$Age <= 30] = "21-30"
titanic$Age_Group[titanic$Age > 30 & titanic$Age <= 40] = "31-40"
titanic$Age_Group[titanic$Age > 40 & titanic$Age <= 50] = "41-50"
titanic$Age_Group[titanic$Age > 50 & titanic$Age <= 60] = "51-60"
titanic$Age_Group[titanic$Age > 60 & titanic$Age <= 70] = "61-70"
titanic$Age_Group[titanic$Age > 70 & titanic$Age <= 80] = "71-80"

titanic$Count = ""
titanic$Count <- as.character(titanic$Count)
titanic$Count = "1"

```



```{r}

# Write CSV in R
write.table(titanic, file = "titanic.csv",row.names=FALSE, na="",col.names=TRUE, sep=",")
```

Rescources:

https://github.com/PMSI-AlignAlytics/dimple/wiki/dimple.color
http://stackoverflow.com/questions/25416063/title-for-charts-and-axes-in-dimple-js-charts
https://bost.ocks.org/mike/bar/